title: The Indifferent

description: >- # this means to ignore newlines until "baseurl:"
  Fiercely ambivalent since 2010
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.theindifferent.co.uk" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: royfox

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

show_excerpts: true
excerpt_separator: <!--more-->

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
